In [1]:
import pandas as pd

In [3]:
# Homework due Monday
# Find the Coldest Temperature (and what hour had it)
# Average Temperature For March 2019

In [2]:
aluksne = pd.read_excel('../data/Aluksne.xls', header=1)
aluksne.head()

,Datums \ Laiks,00:00,01:00,02:00,03:00,04:00,05:00,06:00,07:00,08:00,...,14:00,15:00,16:00,17:00,18:00,19:00,20:00,21:00,22:00,23:00
0,09.02.2019,0.9,1.1,0.9,0.9,0.7,0.5,0.2,0.0,-0.1,...,2.0,2.3,2.4,2.2,2.0,1.6,1.3,1.5,1.6,1.6
1,10.02.2019,1.2,0.9,0.8,0.9,0.6,0.6,0.7,1.1,1.3,...,2.0,1.8,1.7,1.5,1.6,1.4,1.3,1.3,1.5,1.3
2,11.02.2019,1.2,0.9,1.0,0.7,0.9,1.1,0.8,1.0,0.4,...,0.5,0.2,0.2,0.0,0.0,0.0,0.0,0.1,0.0,-0.1
3,12.02.2019,-0.1,0.1,0.1,0.3,0.4,0.6,0.6,0.5,0.3,...,-0.6,-1.3,-1.5,-2.0,-2.6,-2.7,-2.6,-2.6,-2.6,-2.6
4,13.02.2019,-2.8,-2.8,-2.8,-2.8,-2.9,-3.1,-3.6,-5.1,-5.3,...,-1.6,-1.5,-1.5,-1.7,-1.7,-1.7,-1.8,-1.7,-1.6,-1.3